### ISSUE TITLE
Update App-Schema \ HALE workshop

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/nmco#18]
This should follow the improvements suggested in last year report:
https://docs.google.com/document/d/1dzGAv61XpV8MuNdXue44JIgH5ccuIzXQTY0HJPzFmlo/edit#heading=h.o2g0m0qzv7es

**Comment by nmco** [comment]
Concrete of list to include:

- [ ] the introduction should contain a full example of the mapping, or at least a link to where we can refer too

- [ ] coloring should be used to make evident the links between chained features, is always pretty hard to tell people how features are chained together 

- [ ] an almost ready HALE project should be made available, avoiding people to have to do everything by hand

- [ ] a new section should be added (e.g. after the exercises)  where we can contribute the most common errors \ doubts, i.e. some kind of FAQ

Regarding the commons errors \ doubts, I see at least this ones:

- the workspace \ namespace was not defined creating NULL namespaces in the result
- usual property accessors not found error or how to debug a property not encoded
- two types with the same name exist, different mapping names should be used
- using GML3 schema with a GML32 output (geometries not properly encoded)
- WMS throws an exception, is the geometry defined ? how to defined the default geometry ? is a valid style define ?
- how to reference complex nested properties in SLD and OGC filters
-  mapping simple attributes with multiple cardinality
- my query took 20 minutes to execute, what is going on ? (memory filters vs data sources)
- ...

Once we have this list we can make it more complete over time

**Comment by simboss** [comment]
this should go to educations, doing that now

**Comment by nmco** [comment]
Indeed good point, thank you.
