### ISSUE TITLE
Avoid the reprojection of coordinates measures (M)

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/nmco#20]
This should already be supported out of the box with the new JTS API, but it needs to be double checked and a test case should be wrote for this.

child to #14

**Comment by fernandor777** [comment]
Indeed seems like there is not reprojection:

```
<st:position>
        <gml:Point srsDimension="4" srsName="urn:ogc:def:crs:EPSG::4326">
          <gml:pos>1 1 1 4</gml:pos>
        </gml:Point>
      </st:position>
```
vs
```
<st:position>
        <gml:Point srsDimension="4" srsName="urn:ogc:def:crs:EPSG::32717">
          <gml:pos>1.532445099386048E7 1.047333964084083E7 1 4</gml:pos>
        </gml:Point>
      </st:position>
```

**Comment by fernandor777** [comment]
Tests checking no-M-reprojection added on gt-main crs:

https://github.com/fernandor777/geotools/tree/vor21b
https://github.com/fernandor777/geoserver/tree/vor21b
