### ISSUE TITLE
Check that coordinates measures (M) are correctly encoded for complex features too

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/nmco#21]
There is two ways of encoding GML: the "fast one" and the "complex one".

Only one is covered right now, this needs to be double checked with Andrea.

child of #14

**Comment by fernandor777** [comment]
Tests result encoding using a PointZM(1, 1, 1, 4) postgis geometry:

GML 3.1:
<st:position>POINT (1 1)</st:position>

GML 3.2:
<st:position>
        <gml:Point srsDimension="4" srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
          <gml:pos>1 1 1 4</gml:pos>
        </gml:Point>
      </st:position>

**Comment by fernandor777** [comment]
Geotools Fix and test for encoding XYM coordinates to X Y 0 M:

https://github.com/fernandor777/geotools/tree/vor21b
https://github.com/fernandor777/geoserver/tree/vor21b
