### ISSUE TITLE
Make shapefile output format encode coordinates measures (M) when available

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/nmco#22]
Is worth mentioning that input format is not required, we just need to make sure that encoding simple features that have geometries with measures are correctly encoded.

child of #14

**Comment by nmco** [comment]
General tasks we need for this:
- [ ] GeoTools: write output tests for geometries with measures to Shapefile format
- [ ] Geotools: make shapefle correctly output the measures coordinates
- [ ] GeoServer: write integration tests in GeoServer with WFS (GetFeature)

**Comment by fernandor777** [comment]
Branches:
https://github.com/fernandor777/geotools/tree/vor22
https://github.com/fernandor777/geoserver/tree/vor22
