### ISSUE TITLE
Make GeoJSON output format encode coordinates measures (M) when available

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/nmco#23]
GeoServer supports the original GeoJSON spec, which allows to add extra ordinaes as long as there is at least x,y,z (so we'd have to add an elevation to zero, in order to add M).
See: https://github.com/geojson/geojson-spec/blob/master/geojson-spec-draft.rst#positions

child of #14

**Comment by fernandor777** [comment]
Branch:
https://github.com/fernandor777/geoserver/tree/vor23
